from __future__ import annotations

import pygame as pg


class InputMap:
    # Generated by Cursor AI
    def __init__(self) -> None:
        self._pressed: set[int] = set()
        self._just_pressed: set[int] = set()
        self._mb_pressed: set[int] = set()
        self._mb_just_pressed: set[int] = set()

    def begin_frame(self) -> None:
        self._just_pressed.clear()
        self._mb_just_pressed.clear()

    def handle_event(self, e: pg.event.Event) -> None:
        if e.type == pg.KEYDOWN:
            self._pressed.add(e.key)
            self._just_pressed.add(e.key)
        elif e.type == pg.KEYUP:
            self._pressed.discard(e.key)
        elif e.type == pg.MOUSEBUTTONDOWN:
            self._mb_pressed.add(int(e.button))
            self._mb_just_pressed.add(int(e.button))
        elif e.type == pg.MOUSEBUTTONUP:
            self._mb_pressed.discard(int(e.button))

    def down(self, key: int) -> bool:
        return key in self._pressed

    def pressed(self, key: int) -> bool:
        return key in self._just_pressed

    def mouse_down(self, button: int) -> bool:
        return button in self._mb_pressed

    def mouse_pressed(self, button: int) -> bool:
        return button in self._mb_just_pressed

